### ISSUE TITLE
noisy touch trail

### ISSUE THREAD

**Issue by JamesKim2998** [smilingpoplar/CCBlade#2]
hi thanks for nice work! :) 
but touch trail is quite noisy, here is fix. 

change code in 
void TouchTrailLayer::ccTouchesMoved(CCSet *pTouches, CCEvent *pEvent)

CCPoint point = convertTouchToNodeSpace(touch);
CCPoint oldPoint = touch->getPreviousLocation();
point.x = 0.3f \* point.x + 0.7f \* oldPoint.x;
point.y = 0.3f \* point.y + 0.7f \* oldPoint.y;

**Comment by smilingpoplar** [comment]
@geoidn2 thanks
